### ISSUE TITLE
無法複製內容

### ISSUE THREAD

**Issue by weijen6** [qxinGitHub/Remove-web-limits-#3]
https://firmwarex.net/asus-zenfone-3-ze552kl-official-firmware/

**Comment by LTHPKBTE** [comment]
我自己测试是可以的，因为右键菜单被禁用可以按快捷键Ctrl+C复制，或者按住Shift+鼠标右键强制唤出右键菜单复制

**Comment by weijen6** [comment]
感謝，ctrl+c可以，shift+右鍵我這邊也不行
